name: Build and run

on:
  push:
    branches:
      - 'master'
      
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
          
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: test:test
                    
      - name: Test
        run: |
          docker run --rm -e LOG_LEVEL=DEBUG -e ONCE="TRUE" -e SMARTTHINGS_TOKEN=${{ secrets.SMARTTHINGS_TOKEN}} test:test
